name: workflow

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
    build-and-deploy:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '20'
            cache: 'npm'

        - name: Dependencies install
          run: npm ci

        - name: Build
          run: npm run build

        # S3 배포
        - name: AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-northeast-2

        - name : Upload to S3
          run : aws s3 sync ./build s3://my-movie-app-frontend-lsm --delete

        - name : Invalidate CloudFront Cache
          run : aws cloudfront create-invalidation --distribution-id E3PYIO6X39I6NM --paths "/index.html"

#        # 배포
#        - name: Docker Hub Login
#          uses: docker/login-action@v3
#          with:
#            username: ${{ secrets.DOCKER_USERNAME }}
#            password: ${{ secrets.DOCKER_TOKEN }}
#
#        - name: Build and push image
#          uses: docker/build-push-action@v5
#          with:
#            context: .
#            file: ./Dockerfile
#            push: true
#            tags: ${{ secrets.DOCKER_USERNAME }}/my-app-front:latest
#
#        - name: Deploy to Server
#          uses: appleboy/ssh-action@master
#          with:
#            host: ${{ secrets.HOST }}
#            username: ${{ secrets.USERNAME }}
#            key: ${{ secrets.SSH_KEY }}
#            script: |
#              docker pull ${{ secrets.DOCKER_USERNAME }}/my-app-front:latest
#
#              if [ "$(docker ps -a -q -f name=my-front-app)" ]; then
#              docker stop my-front-app
#              docker rm my-front-app
#              fi
#
#              docker run -d \
#                -m 256m \
#                --network my-app-network \
#                --name my-front-app \
#                --restart unless-stopped \
#                ${{ secrets.DOCKER_USERNAME }}/my-app-front:latest